### ISSUE TITLE
Wrong error codes

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#15]
Some error codes are wrongs

1. Empty arguments - Expected `FormulaError { _error: '#NA!' }` 

````
console.log(parser.parse('SUM()', {sheet: 'Sheet 1', row: 1, col: 1}));
````
Received - `Error: Argument type 0 is missing.`

2. Unknown function - Expected `FormulaError { _error: '#NAME?' }` 

```
console.log(parser.parse('SUMABC()', {sheet: 'Sheet 1', row: 1, col: 1}));
```

Received `Error: Function SUMS is not implemented.`

**Comment by LesterLyu** [comment]
I'll look into it.

**Comment by rmdort** [comment]
Opened a PR to fix this https://github.com/LesterLyu/fast-formula-parser/pull/16

**Comment by rmdort** [comment]
Noticed that `SUM(*()` does not throw standard formula error

**Comment by LesterLyu** [comment]
Should be fixed in the new release 👍

**Comment by rmdort** [comment]
In the new release i get `TypeError` for `SUM(*()`

**Comment by LesterLyu** [comment]
I cannot reproduce the error:
https://github.com/LesterLyu/fast-formula-parser/blob/master/test/grammar/errors.js#L92

**Comment by rmdort** [comment]
Oh. It was the dependency parser throwing TypeError.

```
const depParser = new DepParser()
depParser.parse('SUM(*()', { sheet: 'Sheet1', row: 1, col: 1})
```

**Comment by LesterLyu** [comment]
OK, fixed.

**Comment by rmdort** [comment]
Great. thanks
