### ISSUE TITLE
Can all functions access the context?

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#18]
2 issues

1. Functions supplied in `functionsNeedContext` does not work as it throws `function not found` error. This is because we are checking for custom functions in `if (this.functions[name]) {`

2. Right now only `functionsNeedContext` can access context position.  Is there anyway we can inject `context` as the last argument to all functions ? Or the first arg ? Its quite useful when executing side-effects since we know the positions of the cell.

**Comment by LesterLyu** [comment]
- Please provide the sample code where `functionsNeedContext` does not work.
- I cannot inject `context` to all functions, it will mess up internal functions.

**Comment by rmdort** [comment]
Ignore. My bad. Functions defined in `functionsNeedContext` works fine
