### ISSUE TITLE
Inconsistent results with parse and parseAsync

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#19]
If you run

`parser.parse(IF(20 < 0, "yep", "nope"))` => `nope`

With parseAsync

`parser.parseAsync(IF(20 < 0, "yep", "nope"))` => `yep`

Any reason this is happening?

**Comment by LesterLyu** [comment]
https://github.com/LesterLyu/fast-formula-parser/releases/tag/1.0.16

**Comment by rmdort** [comment]
Thank you.
