### ISSUE TITLE
funsNeedContextAndNoDataRetrieve is not in supportedFunctions

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#20]
`supportedFunctions` does not have any functions from `funsNeedContextAndNoDataRetrieve`, Could you add it?

**Comment by LesterLyu** [comment]
https://github.com/LesterLyu/fast-formula-parser/releases/tag/1.0.16

**Comment by rmdort** [comment]
Thanks. All good.
