### ISSUE TITLE
Add support for IFS formulae

### ISSUE THREAD

**Issue by rswheeldon** [LesterLyu/fast-formula-parser#21]
Excel supports IFS formulae in which pairs of (condition, value) are evaluated and the first matching one wins.
e.g.
```
=IFS(1=3,"Not me", 1=2, "Me neither", 1=1, "Yes me")
```
returns
```
Yes me
``` 
fast-formula-parser throws errors when I try and use these.

**Comment by LesterLyu** [comment]
`IFS` is not implemented.

**Comment by LesterLyu** [comment]
Ok. I'll take a look.

**Comment by LesterLyu** [comment]
Updated: https://github.com/LesterLyu/fast-formula-parser/releases/tag/1.0.17

**Comment by rswheeldon** [comment]
That works. Many thanks.
