### ISSUE TITLE
Parsing error with quotes

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#24]
Do you know why i receive parser error with double quotes?

````
import {
  lex,
} from "fast-formula-parser/grammar/lexing";

lex('=SUM("') => Throws parsing error (one double quote)

lex('=SUM('') => Works fine (one single quote)
````

**Comment by LesterLyu** [comment]
The Lexer can not be used to validate grammar. 
You should use a **normal parser**/**dependency parser** to validate grammar.

---

In the Lexer, double quotes are only used to match Strings. That's why `lex('SUM("')` throws an error.
```js
const String = createToken({
    name: 'String',
    pattern: /"(""|[^"])*"/
});
```

**Comment by rmdort** [comment]
Got it thank you
