### ISSUE TITLE
Diagram errors

### ISSUE THREAD

**Issue by danielgesua** [LesterLyu/fast-formula-parser#26]
Hi Lester,

I just noticed some minor errors in your diagram and figured I'd give you a heads up:

Take a look at "functionCall". It's missing the opening parenthesis node.

Also, "postfixOp" does not get used anywhere in the diagram or the code. 

Thanks for this awesome project.

Best,

Daniel Gesua

**Comment by LesterLyu** [comment]
Thanks, got it.
