### ISSUE TITLE
README.md lines 101-106 unnecessary

### ISSUE THREAD

**Issue by danielgesua** [LesterLyu/fast-formula-parser#28]
Hi Lester,

Aren't lines 101-106 of your readme example unnecessary and unreachable due to the first return statement? Or I could be missing some silly fact somewhere.

Thanks,

Daniel Gesua

**Comment by LesterLyu** [comment]
It means you should return one of the two data structure, a **range reference** (A1:B2) or a **single cell reference** (A1).

### Updated README.md
```js
// If it is a range reference (A1:B2)
return {
	sheet: 'sheet name',
	from: {
		row: 1,
		col: 1,
	},
	to: {
		row: 2,
		col: 2,
	}
};
// If it is a cell reference (A1)
return {
	sheet: 'sheet name',
	row: 1,
	col: 1
}
```

**Comment by danielgesua** [comment]
Oh hahaha! Silly me. That's for us to decide. I see
