### ISSUE TITLE
onVariable - access to cell position

### ISSUE THREAD

**Issue by rmdort** [LesterLyu/fast-formula-parser#30]
https://github.com/LesterLyu/fast-formula-parser/blob/master/grammar/hooks.js#L107

Right now, onVariable callbacks has access to variable name and sheet, but not the cell position.

Can i propose to change 

````
const res = {ref: this.onVariable(name, this.position.sheet)};
````

to

````
const res = {ref: this.onVariable(name, this.position)};
````

The reason is that lets say i have a formula `=sales * 10`, in a table. For each onVariable call, i want to access the cell position and return the correct position of `sales` column.

Eg: 

| Sales | total       |
|-------|-------------|
| 11    | =sales * 10 |
| 12    | =sales * 10 |

**Comment by LesterLyu** [comment]
Is this achievable in Excel or Google Sheets?

**Comment by rmdort** [comment]
In Excel tables, it is supported

https://support.microsoft.com/en-us/office/using-structured-references-with-excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e

**Comment by rmdort** [comment]
What do you think of this? Is there any otherway u propose I can access a row index of a variable cell?

**Comment by LesterLyu** [comment]
I'm not familiar with the structured reference, I think I will just make position the third parameter.

**Comment by rmdort** [comment]
Cool thanks. Will be helpful.

**Comment by rmdort** [comment]
Any ETA on v2 release?

**Comment by LesterLyu** [comment]
Not sure yet, could be the beginning of 2021, or the end of 2020.

**Comment by rmdort** [comment]
Wondering if there is a way to access Table names as well `=SUM(DeptSales[Sales Amount])`

`DeptSales => Table and Sales Amount => column name`

More info - https://support.microsoft.com/en-us/office/using-structured-references-with-excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e

**Comment by LesterLyu** [comment]
Implemented in the v2 branch, `position` is now the second parameter.
