### ISSUE TITLE
How to handle formula with dependent arguments containing formula?

### ISSUE THREAD

**Issue by charanjit-singh** [LesterLyu/fast-formula-parser#61]
For example how to handle formula `SUM(A1,B2)` if `A1` is also `=B4-B3`?

**Comment by michaeltford** [comment]
@charanjit-singh this would result in two calculations. 

If the formula is not a cyclical dependency then these must be calced in order. If you need these to be automatic a topological sort could be used.

**Comment by charanjit-singh** [comment]
Thanks @michaeltford ,

Do you have any example?

**Comment by michaeltford** [comment]
@charanjit-singh Not at the moment but I am considering building one in the near future.
