### ISSUE TITLE
onCell return date

### ISSUE THREAD

**Issue by Stevemoretz** [LesterLyu/fast-formula-parser#62]
I can't seem to find a way to return a valid date from inside a variable.

```tsx
  onCell: ({ sheet, row, col }) => {
      return new Date();
      //or
      return [1999,9,9];
      //or
      return "1999-9-9";
      //or
      return "1999/9/9";
  }
```

None of the above works.

**Comment by michaeltford** [comment]
Fast-formula-parser adopts a similar convention to other spreadsheets and manages dates as numbers.  If you want to specify as a string you can use DATEVALUE

```
  import DateFunctions from 'fast-formula-parser/formulas/functions/date';

  onCell: ({ sheet, row, col }) => {
      return DateFunctions.DATEVALUE('1999-9-9');
  }

```

This will return 36412 consistent with Google Sheets and Excel (if you apply number formatting you can see this.)
